import { PopupBase } from "../components/popup_base.slint";
import { Translations } from "../globals/translations.slint";
import { CheckBox, ComboBox, Slider } from "std-widgets.slint";
import { Settings } from "../globals/settings.slint";
import { PopupCenteredText } from "../components/popup_centered_text.slint";

export component PopupOptimizeImage inherits Rectangle {
    in-out property <string> title_text;

    callback action_confirmed();

    out property <length> popup_width: 400px;
    out property <length> popup_height: 280px;
    callback show_popup();

    popup_window := PopupBase {
        width: popup_width;
        height: popup_height;
        title_text <=> root.title_text;

        VerticalLayout {
            spacing: 8px;

            Rectangle { height: 8px; }

            HorizontalLayout {
                spacing: 0px;
                Rectangle { width: 8px; }

                VerticalLayout {
                    spacing: 8px;

                    PopupCenteredText { text: Translations.optimize_image_confirmation_text; }

                    HorizontalLayout {
                        spacing: 5px;
                        Text { text: Translations.optimize_image_target_format_text; vertical_alignment: TextVerticalAlignment.center; }
                        ComboBox {
                            model <=> Settings.image_optimizer_sub_target_format_config;
                            current_index <=> Settings.image_optimizer_sub_target_format_index;
                            current_value <=> Settings.image_optimizer_sub_target_format_value;
                        }
                    }

                    HorizontalLayout {
                        spacing: 5px;
                        Text { text: Translations.optimize_image_quality_text; vertical_alignment: TextVerticalAlignment.center; }
                        Slider { minimum: 1.0; maximum: 100.0; value <=> Settings.image_optimizer_sub_quality; }
                        Text {
                            text: Math.round(Settings.image_optimizer_sub_quality) + " / 100";
                            vertical_alignment: TextVerticalAlignment.center;
                            min-width: 50px;
                        }
                    }

                    CheckBox { text: Translations.optimize_overwrite_files_text; checked <=> Settings.popup_optimize_image_overwrite_files; }
                    CheckBox { text: Translations.preserve_metadata_text; checked <=> Settings.popup_optimize_image_preserve_metadata; }

                    Rectangle { height: 10px; }
                }

                Rectangle { width: 8px; }
            }
        }

        ok_clicked => { root.action_confirmed(); }
        cancel_clicked => { }
    }

    show_popup() => { popup_window.show(); }
}
